version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-jessie-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

      - image: circleci/mysql:5.7
      - image: redis:4.0
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: bundle install

      - run:
          name: run example
          command: ./example
